import re

isocitrate = 'MKTRTQQIEELQKEWTQPRWEGITRPYSAEDVVKLRGSVNPECTLAQLGAAKMWRLLHGE\
              SKKGYINSLGALTGGQALQQAKAGIEAVYLSGWQVAADANLAASMYPDQSLYPANSVPAV\
              VERINNTFRRADQIQWSAGIEPGDPRYVDYFLPIVADAEAGFGGVLNAFELMKAMIEAGA\
AAVHFEDQLASVKKCGHMGGKVLVPTQEAIQKLVAARLAADVTGVPTLLVARTDADAADL\
ITSDCDPYDSEFITGERTSEGFFRTHAGIEQAISRGLAYAPYADLVWCETSTPDLELARR\
FAQAIHAKYPGKLLAYNCSPSFNWQKNLDDKTIASFQQQLSDMGYKFQFITLAGIHSMWF\
NMFDLANAYAQGEGMKHYVEKVQQPEFAAAKDGYTFVSHQQEVGTGYFDKVTTIIQGGTS\
SVTALTGSTEESQF'

x = re.search(r'KKCGHM', isocitrate)
pos = x.start()
site = x.group()
print('{} {} {}{} {}'.format('Isocitrate lyase (P9WKK7) contains its active site (PS00161)', 'starting from', pos, 'th position: ', 'zzz'+site+'zzz'))